const mongoose = require('mongoose');
const Event = require('./models/Event');
const Pro = require('./models/Property');
require('dotenv').config();

// Define your MongoDB connection URI (it's good practice to use an environment variable here)
const mongoURI = "mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.5.3";

mongoose.connect(mongoURI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
})
  .then(() => console.log('Connected to MongoDB'))
  .catch(err => console.error('MongoDB connection error:', err));

const exampleProperties = [
  {
    id: 'prop-001',
    title: 'Modern Apartment with City View',
    address: '15-3 Shibuya, Shibuya-ku, Tokyo',
    price: 850000,
    type: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 950,
    description: 'Bright and spacious apartment located in the heart of Shibuya, offering stunning city views and walking distance to major transport links.',
    imageUrl: 'https://picsum.photos/seed/apartment1/600/400',
    features: { petFriendly: true, parking: false },
    info_text: 'Bright and spacious apartment located in the heart of Shibuya, offering stunning city views and walking distance to major transport links.',
    info_vector: [],
    createdAt: '2024-03-10T10:00:00Z',
  },
  {
    id: 'prop-002',
    title: 'Charming Family House in Meguro',
    address: '8-2 Meguro Honcho, Meguro-ku, Tokyo',
    price: 1200000,
    type: 'house',
    bedrooms: 4,
    bathrooms: 2.5,
    sqft: 1800,
    description: 'A beautiful family home in a quiet, tree-lined street in Meguro. Features a large garden and excellent school district.',
    imageUrl: 'https://picsum.photos/seed/house1/600/400',
    features: { petFriendly: true, parking: true },
    info_text: 'A beautiful family home in a quiet, tree-lined street in Meguro. Features a large garden and excellent school district.',
    info_vector: [],
    createdAt: '2024-02-20T11:30:00Z',
  },
  {
    id: 'prop-003',
    title: 'Cozy Studio near Shinjuku Station',
    address: '2-1 Kabukicho, Shinjuku-ku, Tokyo',
    price: 450000,
    type: 'studio',
    bedrooms: 0,
    bathrooms: 1,
    sqft: 350,
    description: 'Perfect for a single professional. Compact and efficient studio apartment with quick access to Shinjuku Station and vibrant nightlife.',
    imageUrl: 'https://picsum.photos/seed/studio1/600/400',
    features: { petFriendly: false, parking: false },
    info_text: 'Perfect for a single professional. Compact and efficient studio apartment with quick access to Shinjuku Station and vibrant nightlife.',
    info_vector: [],
    createdAt: '2024-04-01T09:15:00Z',
  },
  {
    id: 'prop-004',
    title: 'Spacious Condo in Minato Ward',
    address: '1-1 Azabudai, Minato-ku, Tokyo',
    price: 2500000,
    type: 'condo',
    bedrooms: 3,
    bathrooms: 3.5,
    sqft: 2500,
    description: 'Luxury condominium with panoramic views of Tokyo Tower. Features concierge service and state-of-the-art amenities.',
    imageUrl: 'https://picsum.photos/seed/condo1/600/400',
    features: { petFriendly: false, parking: true },
    info_text: 'Luxury condominium with panoramic views of Tokyo Tower. Features concierge service and state-of-the-art amenities.',
    info_vector: [],
    createdAt: '2024-01-15T14:45:00Z',
  },
  {
    id: 'prop-005',
    title: 'Townhouse with Private Rooftop',
    address: '3-7 Seta, Setagaya-ku, Tokyo',
    price: 1800000,
    type: 'townhouse',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1600,
    description: 'Elegant townhouse with multiple levels and a private rooftop terrace, ideal for entertaining. Quiet residential area.',
    imageUrl: 'https://picsum.photos/seed/townhouse1/600/400',
    features: { petFriendly: true, parking: true },
    info_text: 'Elegant townhouse with multiple levels and a private rooftop terrace, ideal for entertaining. Quiet residential area.',
    info_vector: [],
    createdAt: '2024-05-05T16:00:00Z',
  },
  {
    id: 'prop-006',
    title: 'Compact 1-Bedroom in Ueno',
    address: '4-9 Ueno, Taito-ku, Tokyo',
    price: 600000,
    type: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 500,
    description: 'Affordable 1-bedroom unit close to Ueno Park and museums. Great for students or young professionals.',
    imageUrl: null, // Example without image
    features: { petFriendly: false, parking: false },
    info_text: 'Affordable 1-bedroom unit close to Ueno Park and museums. Great for students or young professionals.',
    info_vector: [],
    createdAt: '2024-06-10T08:00:00Z',
  },
  {
    id: 'prop-007',
    title: 'Executive Apartment in Roppongi',
    address: '7-1 Roppongi, Minato-ku, Tokyo',
    price: 1500000,
    type: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    description: 'High-end apartment in a bustling Roppongi district. Perfect for those who enjoy city life and entertainment.',
    imageUrl: 'https://picsum.photos/seed/roppongi/600/400',
    features: { petFriendly: true, parking: true },
    info_text: 'High-end apartment in a bustling Roppongi district. Perfect for those who enjoy city life and entertainment.',
    info_vector: [],
    createdAt: '2024-03-25T13:00:00Z',
  },
  {
    id: 'prop-008',
    title: 'Renovated House near Tokyo Station',
    address: '1-1 Marunouchi, Chiyoda-ku, Tokyo',
    price: 2000000,
    type: 'house',
    bedrooms: 5,
    bathrooms: 3,
    sqft: 2200,
    description: 'Rare opportunity for a large house in central Tokyo, recently renovated with modern amenities.',
    imageUrl: 'https://picsum.photos/seed/marunouchi/600/400',
    features: { petFriendly: true, parking: true },
    info_text: 'Rare opportunity for a large house in central Tokyo, recently renovated with modern amenities.',
    info_vector: [],
    createdAt: '2024-01-05T10:00:00Z',
  },
  {
    id: 'prop-009',
    title: 'Artist Studio in Shimokitazawa',
    address: '5-1 Kitazawa, Setagaya-ku, Tokyo',
    price: 700000,
    type: 'studio',
    bedrooms: 0,
    bathrooms: 1,
    sqft: 400,
    description: 'Unique studio space in the trendy Shimokitazawa area. Ideal for creatives and young couples.',
    imageUrl: 'https://picsum.photos/seed/shimokita/600/400',
    features: { petFriendly: true, parking: false },
    info_text: 'Unique studio space in the trendy Shimokitazawa area. Ideal for creatives and young couples.',
    info_vector: [],
    createdAt: '2024-05-20T17:00:00Z',
  },
  {
    id: 'prop-010',
    title: 'Family-Friendly Apartment in Kichijoji',
    address: '2-1 Kichijoji Honcho, Musashino-shi, Tokyo',
    price: 950000,
    type: 'apartment',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1100,
    description: 'Spacious 3-bedroom apartment in a highly sought-after, family-friendly neighborhood. Close to Inokashira Park.',
    imageUrl: 'https://picsum.photos/seed/kichijoji/600/400',
    features: { petFriendly: true, parking: true },
    info_text: 'Spacious 3-bedroom apartment in a highly sought-after, family-friendly neighborhood. Close to Inokashira Park.',
    info_vector: [],
    createdAt: '2024-04-12T09:45:00Z',
  },
  {
    id: 'prop-011',
    title: 'Luxury Penthouse in Ginza',
    address: '6-1 Ginza, Chuo-ku, Tokyo',
    price: 3000000,
    type: 'condo',
    bedrooms: 4,
    bathrooms: 4.5,
    sqft: 3500,
    description: 'Unparalleled luxury living in Ginza, with private elevator access and breathtaking panoramic city views.',
    imageUrl: 'https://picsum.photos/seed/ginza1/600/400',
    features: { petFriendly: false, parking: true },
    info_text: 'Unparalleled luxury living in Ginza, with private elevator access and breathtaking panoramic city views.',
    info_vector: [],
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'prop-012',
    title: 'Cozy House in Suburb',
    address: '1-1 Suburbia, Fuchu-shi, Tokyo',
    price: 750000,
    type: 'house',
    bedrooms: 3,
    bathrooms: 1.5,
    sqft: 1400,
    description: 'A charming, well-maintained house in a quiet suburban neighborhood with good commuter access.',
    imageUrl: 'https://picsum.photos/seed/suburb1/600/400',
    features: { petFriendly: true, parking: true },
    info_text: 'A charming, well-maintained house in a quiet suburban neighborhood with good commuter access.',
    info_vector: [],
    createdAt: '2024-03-01T15:00:00Z',
  },
  {
    id: 'prop-013',
    title: 'Bachelor Pad in Shibuya',
    address: '10-5 Dogenzaka, Shibuya-ku, Tokyo',
    price: 550000,
    type: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    description: 'Sleek and modern 1-bedroom apartment, perfect for singles. Close to nightlife and entertainment.',
    imageUrl: 'https://picsum.photos/seed/bachelor/600/400',
    features: { petFriendly: false, parking: false },
    info_text: 'Sleek and modern 1-bedroom apartment, perfect for singles. Close to nightlife and entertainment.',
    info_vector: [],
    createdAt: '2024-06-01T12:00:00Z',
  },
  {
    id: 'prop-014',
    title: 'Renovated Townhouse in Setagaya',
    address: '4-2 Tamagawa, Setagaya-ku, Tokyo',
    price: 1600000,
    type: 'townhouse',
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 1750,
    description: 'Recently renovated townhouse with high-end finishes and a small backyard space. Excellent for families.',
    imageUrl: 'https://picsum.photos/seed/seta2/600/400',
    features: { petFriendly: true, parking: true },
    info_text: 'Recently renovated townhouse with high-end finishes and a small backyard space. Excellent for families.',
    info_vector: [],
    createdAt: '2024-04-20T11:00:00Z',
  },
  {
    id: 'prop-015',
    title: 'High-Rise Condo in Shinjuku',
    address: '3-2 Nishi-Shinjuku, Shinjuku-ku, Tokyo',
    price: 1900000,
    type: 'condo',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1300,
    description: 'Luxurious condo on a high floor with incredible views of the Shinjuku skyline. Access to gym and pool.',
    imageUrl: 'https://picsum.photos/seed/shinjuku2/600/400',
    features: { petFriendly: false, parking: true },
    info_text: 'Luxurious condo on a high floor with incredible views of the Shinjuku skyline. Access to gym and pool.',
    info_vector: [],
    createdAt: '2024-02-10T14:00:00Z',
  },
  {
    id: 'prop-016',
    title: 'Small House, Big Garden',
    address: '9-1 Kitasenzoku, Ota-ku, Tokyo',
    price: 800000,
    type: 'house',
    bedrooms: 2,
    bathrooms: 1,
    sqft: 1000,
    description: 'A cute little house with a surprisingly large garden, perfect for outdoor enthusiasts. Quiet residential street.',
    imageUrl: 'https://picsum.photos/seed/gardenhouse/600/400',
    features: { petFriendly: true, parking: true },
    info_text: 'A cute little house with a surprisingly large garden, perfect for outdoor enthusiasts. Quiet residential street.',
    info_vector: [],
    createdAt: '2024-05-15T09:00:00Z',
  },
  {
    id: 'prop-017',
    title: 'Riverside Apartment',
    address: '1-1 Sumida, Sumida-ku, Tokyo',
    price: 700000,
    type: 'apartment',
    bedrooms: 2,
    bathrooms: 1.5,
    sqft: 850,
    description: 'Apartment with charming views of the Sumida River. Easy access to Asakusa and Skytree.',
    imageUrl: 'https://picsum.photos/seed/riverside/600/400',
    features: { petFriendly: false, parking: false },
    info_text: 'Apartment with charming views of the Sumida River. Easy access to Asakusa and Skytree.',
    info_vector: [],
    createdAt: '2024-03-05T10:30:00Z',
  },
  {
    id: 'prop-018',
    title: 'Modern Japanese House',
    address: '5-5 Nerima, Nerima-ku, Tokyo',
    price: 1100000,
    type: 'house',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1500,
    description: 'Newly built modern Japanese style house with efficient layout and natural light. Good public transport access.',
    imageUrl: 'https://picsum.photos/seed/japanhouse/600/400',
    features: { petFriendly: true, parking: true },
    info_text: 'Newly built modern Japanese style house with efficient layout and natural light. Good public transport access.',
    info_vector: [],
    createdAt: '2024-02-28T16:00:00Z',
  },
  {
    id: 'prop-019',
    title: 'Student-Friendly Studio',
    address: '7-1 Hongo, Bunkyo-ku, Tokyo',
    price: 350000,
    type: 'studio',
    bedrooms: 0,
    bathrooms: 1,
    sqft: 280,
    description: 'Affordable studio apartment ideal for students, very close to Tokyo University campus.',
    imageUrl: null,
    features: { petFriendly: false, parking: false },
    info_text: 'Affordable studio apartment ideal for students, very close to Tokyo University campus.',
    info_vector: [],
    createdAt: '2024-06-20T09:00:00Z',
  },
  {
    id: 'prop-020',
    title: 'Cozy Condo for Couples',
    address: '2-3 Futako-Tamagawa, Setagaya-ku, Tokyo',
    price: 900000,
    type: 'condo',
    bedrooms: 2,
    bathrooms: 1.5,
    sqft: 900,
    description: 'Comfortable condo in the popular Futako-Tamagawa area, perfect for couples. Shops and restaurants nearby.',
    imageUrl: 'https://picsum.photos/seed/futako/600/400',
    features: { petFriendly: true, parking: false },
    info_text: 'Comfortable condo in the popular Futako-Tamagawa area, perfect for couples. Shops and restaurants nearby.',
    info_vector: [],
    createdAt: '2024-04-05T13:30:00Z',
  },
  {
    id: 'prop-021',
    title: 'Expansive Urban House',
    address: '1-10 Hiroo, Shibuya-ku, Tokyo',
    price: 2800000,
    type: 'house',
    bedrooms: 5,
    bathrooms: 4,
    sqft: 3000,
    description: 'A rare find: a large family house in the desirable Hiroo neighborhood, with modern design and amenities.',
    imageUrl: 'https://picsum.photos/seed/hiroo/600/400',
    features: { petFriendly: true, parking: true },
    info_text: 'A rare find: a large family house in the desirable Hiroo neighborhood, with modern design and amenities.',
    info_vector: [],
    createdAt: '2024-01-25T11:00:00Z',
  },
  {
    id: 'prop-022',
    title: 'Stylish Apartment in Jiyugaoka',
    address: '1-2 Jiyugaoka, Meguro-ku, Tokyo',
    price: 1050000,
    type: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1000,
    description: 'Designer apartment in the trendy Jiyugaoka area. Enjoy boutique shops and cafes just steps away.',
    imageUrl: 'https://picsum.photos/seed/jiyugaoka/600/400',
    features: { petFriendly: false, parking: true },
    info_text: 'Designer apartment in the trendy Jiyugaoka area. Enjoy boutique shops and cafes just steps away.',
    info_vector: [],
    createdAt: '2024-05-01T15:00:00Z',
  },
  {
    id: 'prop-023',
    title: 'Compact Townhouse for Singles',
    address: '6-1 Sendagaya, Shibuya-ku, Tokyo',
    price: 900000,
    type: 'townhouse',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 700,
    description: 'Small but perfectly formed townhouse, ideal for a single person seeking a quiet urban retreat.',
    imageUrl: 'https://picsum.photos/seed/sendagaya/600/400',
    features: { petFriendly: true, parking: false },
    info_text: 'Small but perfectly formed townhouse, ideal for a single person seeking a quiet urban retreat.',
    info_vector: [],
    createdAt: '2024-03-18T10:00:00Z',
  },
  {
    id: 'prop-024',
    title: 'Studio with Balcony Access',
    address: '4-4 Ikebukuro, Toshima-ku, Tokyo',
    price: 480000,
    type: 'studio',
    bedrooms: 0,
    bathrooms: 1,
    sqft: 380,
    description: 'Bright studio with a small balcony, perfect for morning coffee. Conveniently located near Ikebukuro Station.',
    imageUrl: 'https://picsum.photos/seed/ikebukuro/600/400',
    features: { petFriendly: false, parking: false },
    info_text: 'Bright studio with a small balcony, perfect for morning coffee. Conveniently located near Ikebukuro Station.',
    info_vector: [],
    createdAt: '2024-06-05T14:00:00Z',
  },
  {
    id: 'prop-025',
    title: 'Luxury Apartment for Executives',
    address: '9-3 Akasaka, Minato-ku, Tokyo',
    price: 1700000,
    type: 'apartment',
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 1400,
    description: 'Premium apartment in the prestigious Akasaka district, tailored for executive living. High-end finishes throughout.',
    imageUrl: 'https://picsum.photos/seed/akasaka/600/400',
    features: { petFriendly: false, parking: true },
    info_text: 'Premium apartment in the prestigious Akasaka district, tailored for executive living. High-end finishes throughout.',
    info_vector: [],
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'prop-026',
    title: 'Classic Japanese House',
    address: '2-1 Yanaka, Taito-ku, Tokyo',
    price: 980000,
    type: 'house',
    bedrooms: 4,
    bathrooms: 2,
    sqft: 1600,
    description: 'Traditional Japanese house with a serene garden, located in the historic Yanaka district. A peaceful oasis.',
    imageUrl: 'https://picsum.photos/seed/yanaka/600/400',
    features: { petFriendly: true, parking: true },
    info_text: 'Traditional Japanese house with a serene garden, located in the historic Yanaka district. A peaceful oasis.',
    info_vector: [],
    createdAt: '2024-04-28T11:00:00Z',
  },
  {
    id: 'prop-027',
    title: 'City Center Condo',
    address: '1-1 Kudanshita, Chiyoda-ku, Tokyo',
    price: 1300000,
    type: 'condo',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1050,
    description: 'Conveniently located condo in the heart of the city, with easy access to business districts and parks.',
    imageUrl: 'https://picsum.photos/seed/kudanshita/600/400',
    features: { petFriendly: false, parking: true },
    info_text: 'Conveniently located condo in the heart of the city, with easy access to business districts and parks.',
    info_vector: [],
    createdAt: '2024-03-12T09:30:00Z',
  },
  {
    id: 'prop-028',
    title: 'Spacious 1-Bedroom Apartment',
    address: '3-8 Nakameguro, Meguro-ku, Tokyo',
    price: 780000,
    type: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 750,
    description: 'Generously sized 1-bedroom apartment in the vibrant Nakameguro area, known for its canals and cafes.',
    imageUrl: 'https://picsum.photos/seed/nakameguro/600/400',
    features: { petFriendly: true, parking: false },
    info_text: 'Generously sized 1-bedroom apartment in the vibrant Nakameguro area, known for its canals and cafes.',
    info_vector: [],
    createdAt: '2024-05-25T16:00:00Z',
  },
  {
    id: 'prop-029',
    title: 'Modern Townhouse with Garage',
    address: '8-1 Kitasenzoku, Ota-ku, Tokyo',
    price: 1400000,
    type: 'townhouse',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1650,
    description: 'Contemporary townhouse featuring an integrated garage and a small private patio. Ideal for small families.',
    imageUrl: 'https://picsum.photos/seed/garagehouse/600/400',
    features: { petFriendly: true, parking: true },
    info_text: 'Contemporary townhouse featuring an integrated garage and a small private patio. Ideal for small families.',
    info_vector: [],
    createdAt: '2024-02-05T13:00:00Z',
  },
  {
    id: 'prop-030',
    title: 'Executive Studio for Singles',
    address: '2-1 Kagurazaka, Shinjuku-ku, Tokyo',
    price: 520000,
    type: 'studio',
    bedrooms: 0,
    bathrooms: 1,
    sqft: 420,
    description: 'Compact yet luxurious studio in the charming Kagurazaka neighborhood. Perfect for a busy professional.',
    imageUrl: 'https://picsum.photos/seed/kagurazaka/600/400',
    features: { petFriendly: false, parking: false },
    info_text: 'Compact yet luxurious studio in the charming Kagurazaka neighborhood. Perfect for a busy professional.',
    info_vector: [],
    createdAt: '2024-06-15T08:30:00Z',
  },
];

// You can use this array in your component's state initialization:
// const [properties, setProperties] = useState(exampleProperties);
// const [filteredProperties, setFilteredProperties] = useState(exampleProperties);


async function seedDatabase() {
  try {
    // Clear existing events (optional, remove if you want to append)
    await Pro.deleteMany({});
    console.log('Cleared existing events');

    // Insert new events
    await Pro.insertMany(exampleProperties);
    console.log('Successfully seeded events');

    // Close connection
    mongoose.connection.close();
  } catch (error) {
    console.error('Error seeding database:', error);
    mongoose.connection.close();
  }
}

seedDatabase();